# This is a basic workflow to help you get started with Actions

name: SFDX Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v2

      # Install SFDX CLI and authenticate
      - name: Salesforce SFDX CLI Setup
        uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.DEVHUB_URL }}

      # Set default DevHub org for us to create scratch orgs and package against 
      - name: Set Default DevHub
        run: sfdx force:config:set defaultdevhubusername=test-cip5cl81f6zt@example.com

      # Create a scratch org to test our code
      - name: Create Scratch Org
        run: sfdx force:org:create -a actionBuild -d 1 -f config/project-scratch-def.json -s

      # Pushes all configuration to scratch org
      - name: Pushing source
        run: sfdx force:source:push -f

      # Run all Apex tests in our Scratch org
      - name: Running Apex Test
        run: sfdx force:apex:test:run -l RunLocalTests -w 30

      # Delete scratch org after successful build
      - name: Deleteing Scratch Org
        run: sfdx force:org:delete -p  

     
